MyNurseApp/Controllers/ManipulationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNurseApp.Services.Data.Interfaces;
using MyNurseApp.Web.ViewModels.Manipulations;
using Newtonsoft.Json;


namespace MyNurseApp.Controllers
{
    [Authorize]
    public class ManipulationsController : BaseController
    {
        private readonly IManipulationsService _manipulationsService;
        public ManipulationsController(IManipulationsService manipulationsService)
        {
            _manipulationsService = manipulationsService;
        }

        [HttpGet]
        public IActionResult SaveSelection()
        {
            var selectedManipulations = GetFromTempData<MedicalManipulationsViewModel>("SelectedManipulations", this);

            HttpContext.Session.SetString("SelectedManipulations", JsonConvert.SerializeObject(selectedManipulations));
            ClearTempData("SelectedManipulations", this);
            return RedirectToAction("Schedule", "Schedule");
        }

        [HttpGet]
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 7)
        {
            var selectedManipulations = GetFromTempData<MedicalManipulationsViewModel>("SelectedManipulations", this);

            ViewBag.SelectedManipulations = selectedManipulations;

            var manipulations = await _manipulationsService.GetAllManipulationsAsync(pageNumber,pageSize);
            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((double)_manipulationsService.GetTotalCount() / pageSize);
            return View(manipulations);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToSelection(Guid id)
        {
            var manipulation = _manipulationsService.GetByIdAsync(id).Result;
            AddToTempData("SelectedManipulations", manipulation, this);
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ClearSelection()
        {
            ClearTempData("SelectedManipulations", this);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddManipulation()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddManipulation(MedicalManipulationsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _manipulationsService.AddManipulationAsync(model);
                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(Index));
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveManipulation(Guid id)
        {
            try
            {
                await _manipulationsService.RemoveManipulationAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditManipulation(Guid id)
        {
            var model = await _manipulationsService.GetByIdAsync(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditManipulation(MedicalManipulationsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            await _manipulationsService.EditManipulationAsync(model);
            return RedirectToAction("Index");
        }


        public void AddToTempData<T>(string key, T item, Controller controller)
        {
            var existingData = controller.TempData[key] as string;
            var list = string.IsNullOrEmpty(existingData)
                ? new List<T>()
                : JsonConvert.DeserializeObject<List<T>>(existingData);

            list!.Add(item);

            controller.TempData[key] = JsonConvert.SerializeObject(list);
        }

        public List<T> GetFromTempData<T>(string key, Controller controller)
        {
            var data = controller.TempData.Peek(key) as string;
            return string.IsNullOrEmpty(data)
                ? new List<T>()
                : JsonConvert.DeserializeObject<List<T>>(data)!;
        }

        public void ClearTempData(string key, Controller controller)
        {
            controller.TempData[key] = null;
        }

        [HttpGet]
        public async Task<IActionResult> SearchMedicalManipulations(string query)
        {
            var manipulations = await _manipulationsService.SearchManipulationsAsync(query);
            return PartialView("_MedicalManipulationsList", manipulations);
        }
    }
}

MyNurseApp/Controllers/NurseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNurseApp.Services.Data.Interfaces;
using MyNurseApp.Web.ViewModels.NurseProfile;

namespace MyNurseApp.Controllers
{
    [Authorize]
    public class NurseController : BaseController
    {
        private readonly INurseService _nurseService;

        public NurseController(INurseService nurseService)
        {
            this._nurseService = nurseService;
        }

        public async Task<IActionResult> Profile()
        {
            try
            {
                var viewModels = await _nurseService.GetNurseProfileAsync();
                return View(viewModels);
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, "Error", "Home");
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditNurseProfile()
        {
            try
            {
                var profile = await _nurseService.GetNurseProfileAsync();
                return View(profile);
            }
            catch (InvalidOperationException ex)
            {

                return HandleError(ex, nameof(Profile));

            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditNurseProfile(NurseProfileViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await _nurseService.EditNurseProfileAync(model);
                return RedirectToAction(nameof(Profile));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(Profile));

            }
        }


        [HttpGet]
        public async Task<IActionResult> RequestedVisitations()
        {
            var viewModels = await _nurseService.GetNurseHomeVisitatonsAync();
            return View(viewModels);
        }

        [HttpGet]
        public async Task<IActionResult> FinishVisitaion(Guid id)
        {
            try
            {
                await _nurseService.GetNurseHomeVisitatonsAync(id);
                return RedirectToAction(nameof(RequestedVisitations));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(RequestedVisitations));
            }
        }


        [HttpGet]
        public async Task<IActionResult> CreateNurseProfile()
        {
            var viewModels = await _nurseService.GetNurseProfileAsync();
            if (viewModels != null)
            {
                return RedirectToAction(nameof(Profile), viewModels);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateNurseProfile(NurseProfileViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await _nurseService.RegisterNurseAsync(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GetAllNursesProfiles()
        {
            var viewModels = await _nurseService.GetAllNursesAsync();
            return View(viewModels);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AprooveNurse(Guid id)
        {
            await _nurseService.AprooveNurseAync(id);
            return RedirectToAction(nameof(GetAllNursesProfiles));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeclineNurse(Guid id)
        {
            await _nurseService.DeclineNurseAync(id);
            return RedirectToAction(nameof(GetAllNursesProfiles));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteNurseProfile(Guid id)
        {
            try
            {
                await _nurseService.DeleteNurseProfileAync(id);
                return RedirectToAction(nameof(GetAllNursesProfiles));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(GetAllNursesProfiles));
            }
        }
    }
}

MyNurseApp/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNurseApp.Services.Data.Interfaces;
using MyNurseApp.Web.ViewModels.Review;

namespace MyNurseApp.Controllers
{

    public class ReviewController : BaseController
    {

        private readonly IReviewService _reviewService;

        public ReviewController(IReviewService reviewService)
        {
            this._reviewService = reviewService;
        }

        public async Task<IActionResult> Index()
        {
            var models = await _reviewService.GetAllReviewsAsync();
            return View(models);
        }

        [HttpGet]
        [Authorize]
        public IActionResult CreateReview()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateReview(ReviewViewModel model)
        {
            try
            {
                await _reviewService.CreateReviewAsync(model);
                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(Index));
            }
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteReview(Guid id)
        {
            try
            {
                await _reviewService.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(Index));
            }
        }

    }
}

MyNurseApp/Controllers/ScheduleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyNurseApp.Services.Data.Interfaces;
using MyNurseApp.Web.ViewModels;
using MyNurseApp.Web.ViewModels.HomeVisitation;
using MyNurseApp.Web.ViewModels.Manipulations;
using MyNurseApp.Web.ViewModels.PatientProfile;
using Newtonsoft.Json;

namespace MyNurseApp.Controllers
{
    [Authorize]
    public class ScheduleController : BaseController
    {
        private readonly IScheduleService _scheduleService;
        private readonly INurseService _nurseService;
        public ScheduleController(IScheduleService scheduleService, INurseService nurseService)
        {
            _scheduleService = scheduleService;
            _nurseService = nurseService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await _scheduleService.GetVisitationsForUserAsync();
            if (model == null)
            {
                return RedirectToAction("CreatePatientProfile", "PatientProfile");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteHomeVisitationFromPatient(Guid visitationId)
        {
            try
            {
                await _scheduleService.DeleteHomeVisitationAsync(visitationId);
                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(Index));

            }
        }

        [HttpGet]
        public async Task<IActionResult> Schedule()
        {
            List<MedicalManipulationsViewModel> selectedManipulations = GetSelectedManipulations();
            PatientProfileViewModel patientModel = new PatientProfileViewModel();
            try
            {
                patientModel = await _scheduleService.GetPatientAync();
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, "Error", "Home");
            }
            HomeVisitationViewModel homeVisitation = new HomeVisitationViewModel()
            {
                DateTimeManipulation = DateTime.Today
            };

            PatientAndHomeVisitationViewModel viewModel = new PatientAndHomeVisitationViewModel()
            {
                HomeVisitation = homeVisitation,
                PatientProfile = patientModel,
                MedicalManipulations = selectedManipulations!
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Schedule(PatientAndHomeVisitationViewModel model)
        {

            List<MedicalManipulationsViewModel> selectedManipulations = GetSelectedManipulations();
            PatientProfileViewModel patientModel = new PatientProfileViewModel();

            try
            {
                patientModel = await _scheduleService.GetPatientAync();
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, "Error", "Home");
            }

            model.MedicalManipulations = selectedManipulations;
            model.PatientProfile = patientModel;

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await _scheduleService.AddHomeVisitationAsync(model);
                return RedirectToAction(nameof(Index));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(Index));
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GetAllHomeVisitations()
        {
            var nurses = await _nurseService.GetAllNursesAsync();
            ViewData["Nurses"] = nurses;
            var viewModel = await _scheduleService.GetAllVisitationsAsync();
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> AssignVisitationToNurse(Guid visitationId, Guid nurseId)
        {
            try
            {
                await _scheduleService.AssignVisitationToNurseAsync(visitationId, nurseId);
                return RedirectToAction(nameof(GetAllHomeVisitations));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(GetAllHomeVisitations));
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteHomeVisitation(Guid visitationId)
        {
            try
            {
                await _scheduleService.DeleteHomeVisitationAsync(visitationId);
                return RedirectToAction(nameof(GetAllHomeVisitations));
            }
            catch (InvalidOperationException ex)
            {
                return HandleError(ex, nameof(GetAllHomeVisitations));
            }
        }


        private List<MedicalManipulationsViewModel> GetSelectedManipulations()
        {
            var manipulationsJson = HttpContext.Session.GetString("SelectedManipulations");

            List<MedicalManipulationsViewModel>? selectedManipulations = manipulationsJson != null
                ? JsonConvert.DeserializeObject<List<MedicalManipulationsViewModel>>(manipulationsJson)
                : new List<MedicalManipulationsViewModel>();

            return selectedManipulations!;
        }
    }
}

MyNurseApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyNurseApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyNurseApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manipulations" asp-action="Index">Manipulations</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Nurse" asp-action="GetAllNursesProfiles">Nurses Profiles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="PatientProfile" asp-action="GetAllPatientsProfiles">Patients Profiles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Schedule" asp-action="GetAllHomeVisitations">Schedules</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AdminInformation" asp-action="Index">All Profiles</a>
                            </li>
                        }
                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="PatientProfile" asp-action="Index">Patient Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Schedule" asp-action="Index">Patient Schedule</a>
                            </li>
                        }
                        @if (User.IsInRole("Nurse"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Nurse" asp-action="Profile">Nurse Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Nurse" asp-action="RequestedVisitations">Requests</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Review" asp-action="Index">Reviews</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyNurseApp  <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>